"""
End-to-end smoke test:
intent parser -> gen_followup -> parse follow-up answers -> gen_list.

Run from repo root:
  .venv\\Scripts\\python.exe -m backend.services.tester
Optional: pass the user message as argv (use single quotes in PowerShell if it contains $).
"""

from __future__ import annotations

import json
import sys
from typing import Any

from backend.services.gen_followup import gen_followup
from backend.services.gen_list import gen_list
from backend.services.intent_parser import parse_intent

# Natural-language query the parser fills from (edit freely).
CUSTOM_USER_MESSAGE = (
    "I want to get into bonsai tree planting. I'm a beginner and I'm in the Bay Area. My budget is $500"
)

# Natural-language answer to the follow-up questions generated by gen_followup.
FOLLOWUP_USER_MESSAGE = (
    "I want an indoor tree, something forgiving for beginners, and I can water it a few times a week."
)

# Intent template the model must fill (same keys as tool output; raw_query is added by parse_intent).
SKELETON: dict[str, Any] = {
    "hobby": None,
    "budget_usd": None,
    "location": None,
    "skill_level": None,
    "other": None,
}

INCLUDE_HOBBY_OTHER_FLAGS = True


def main() -> None:
    text = " ".join(sys.argv[1:]).strip() if len(sys.argv) > 1 else CUSTOM_USER_MESSAGE
    print("[tester] 1/4 parsing initial user prompt...", file=sys.stderr)
    intent = parse_intent(text, SKELETON)
    merged_for_db: dict[str, Any] = {}
    print("[tester] 2/4 generating follow-up questions...", file=sys.stderr)
    out = gen_followup(
        intent,
        include_hobby_other_flags=INCLUDE_HOBBY_OTHER_FLAGS,
        merged_intent_out=merged_for_db,
    )
    print("[tester] 3/4 parsing follow-up response...", file=sys.stderr)
    completed_intent = parse_intent(FOLLOWUP_USER_MESSAGE, merged_for_db)
    print("[tester] 4/4 generating shopping list...", file=sys.stderr)
    shopping_list = gen_list(completed_intent)
    print("[tester] done", file=sys.stderr)
    print(
        json.dumps(
            {
                "parsed_intent": intent,
                "gen_followup": out,
                "merged_intent_for_db": merged_for_db,
                "completed_intent_for_gen_list": completed_intent,
                "gen_list": shopping_list,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
